# --- Configurações Globais ---
server.port=8080
spring.application.name=financeiro-core-service

# --- API Documentation ---
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# --- Ativação de Perfil (Opcional) ---
# Você pode deixar comentado para rodar o padrão, 
# ou ativar o oracle aqui se for o seu padrão principal.
# spring.profiles.active=oracle

# --- Dica de Sênior: Fallback de Segurança ---
# Isso garante que a aplicação não tente conectar no banco sem os segredos definidos
# Se faltar a variável de ambiente, ele falhará rápido (fail-fast)
spring.datasource.url=${SPRING_DATASOURCE_URL}