# --- Configurações do Servidor ---
server.port=8082
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}

# --- Conexão com Oracle ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xe
spring.datasource.username=SYSTEM
spring.datasource.password=${NV_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- Otimização e JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# --- Pool de Conexões Hikari (Estabilidade no Docker) ---
spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10

# --- Logs e Debug ---
server.error.whitelabel.enabled=false
spring.jackson.serialization.indent-output=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Se precisar forçar a desativação de metadados JDBC no futuro, descomente a linha abaixo:
# spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false