# Configurações do servidor
server.port=8082

# Conexão com Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system    
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Dialeto do Hibernate para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# DDL: 'update' permite que o Hibernate crie/atualize suas tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Configuração de performance (mantemos o false para boas práticas)
spring.jpa.open-in-view=false

# Garante que o erro customizado não seja sobreposto pela página padrão
server.error.whitelabel.enabled=false

# Melhora a exibição do JSON no console e logs
spring.jackson.serialization.indent-output=true