# --- Configurações Globais ---
server.port=8080
spring.application.name=financeiro-core-service

# --- API Documentation ---
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# --- Ativação de Perfil ---
# Ativa o perfil 'oracle' para carregar as configurações do application-oracle.properties
spring.profiles.active=oracle

# --- Dica de Sênior: Fallback de Segurança ---
# Tenta ler a variável de ambiente, se não existir, usa o padrão local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521:xe}