# Conexão com Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system   
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Dialeto do Hibernate para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# DDL: 'update' permite que o Hibernate crie/atualize suas tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Configuração de performance (mantemos o false para boas práticas)
spring.jpa.open-in-view=false